### ISSUE TITLE
Majority of stack sampling dumps are empty

### ISSUE THREAD

**Issue by chrisheaththomas** [jamespic/pyspark-flame#2] opened 2018-12-17 10:16 UTC
Although pyspark-flame successfully produces stack sampling dumps for a couple of RDDs in our script, the majority of .flame files are empty.

Environment is emr-5.17.0, pyspark-flame-0.2.6.

**Comment by jamespic** [comment] 2018-12-17 12:17
I haven't done much with EMR, so you might need to hand-hold me through reproducing this one. A test case or some steps to reproduce would be best. 

Off the top of my head, the most obvious reasons I can think of that this might happen:

- Most partitions complete very quickly (less than a quarter of a second, or so). Pyspark-flame takes a stack trace periodically, so if the time taken to run a partition is less than this period, you won't get any data. If you've used a large number of partitions, then this is the time taken for each partition.
- You're doing a lot of work that holds onto the global interpreter lock (maybe some native stuff), so the profiling thread isn't being scheduled.

If none of these ring a bell, then some steps to reproduce should help me get further. You might also look at PyFlame, which may give some insight into what's going on, as well as being a useful profiler in its own right.

**Comment by chrisheaththomas** [comment] 2018-12-17 16:05
Thanks for the feedback James. From experiments this afternoon, I am reasonably confident that the issue is an incompatibility with Dataframes. I get sampling dumps when I use an RDD, but not when I switch to using a Dataframe.

**Comment by jamespic** [comment] 2018-12-17 18:24
That makes sense. If I remember rightly, I think a lot of the heavy lifting for data frames happens in Scala, and Pyspark-flame can't see into Scala code. But I'll see if I can get a test case to confirm this.

**Comment by jamespic** [comment] 2019-03-03 17:06
Yes, it looks like dataframes don't run Python RDD code on the workers (it's all implemented in Scala), so pyspark-flame has no way of seeing into the process.

I'm closing this, because I don't think there's a good way to solve it from Python. This seems like something that's better solved from within the JVM.

**Closed as completed by jamespic** 2019-03-03 17:06 UTC

**Comment by AlJohri** [comment] 2019-07-09 16:32
Dropping this link here https://github.com/spektom/spark-flamegraph

**Comment by jamespic** [comment] 2019-07-09 17:43
@AlJohri cool! It's good that someone's got something for the Java side of things. It's not something I've done much on, because the project this was created for is mostly RDDs, but might be worthwhile in the future.

If I do add something like this, the approach that project takes is a little heavyweight, and has some characteristics that'll be problematic for the project I'm currently on (needs to work without Internet access, for example), but a more lightweight version should be possible.
